apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: server-app
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
      
